# Generated by Django 3.2.7 on 2022-02-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
